version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - cluster.routing.allocation.disk.watermark.low=85%
      - cluster.routing.allocation.disk.watermark.high=95%
      - cluster.routing.allocation.disk.watermark.flood_stage=98%
      - ingest.geoip.downloader.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet

  python-app:
    build: .
    container_name: python-app
    volumes:
      - ./scripts:/app  # Mount the . directory to '/app' in the 
    networks:
      - esnet
    depends_on:
      - elasticsearch
    entrypoint: ["tail", "-f", "/dev/null"] 

networks:
  esnet:
    driver: bridge